parameters:
    band_context:
        excluded_routes:
            - app_login
            - app_register
            - app_band_create
            - app_band_create_modal
        redirect_to: app_band_create

